// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: ordercart/ordercart.proto

package ordercart

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderCostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cart []*Item `protobuf:"bytes,1,rep,name=cart,proto3" json:"cart,omitempty"`
}

func (x *OrderCostRequest) Reset() {
	*x = OrderCostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ordercart_ordercart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCostRequest) ProtoMessage() {}

func (x *OrderCostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ordercart_ordercart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCostRequest.ProtoReflect.Descriptor instead.
func (*OrderCostRequest) Descriptor() ([]byte, []int) {
	return file_ordercart_ordercart_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCostRequest) GetCart() []*Item {
	if x != nil {
		return x.Cart
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ordercart_ordercart_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_ordercart_ordercart_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_ordercart_ordercart_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type OrderCostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cost string `protobuf:"bytes,1,opt,name=cost,proto3" json:"cost,omitempty"`
}

func (x *OrderCostResponse) Reset() {
	*x = OrderCostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ordercart_ordercart_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCostResponse) ProtoMessage() {}

func (x *OrderCostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ordercart_ordercart_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCostResponse.ProtoReflect.Descriptor instead.
func (*OrderCostResponse) Descriptor() ([]byte, []int) {
	return file_ordercart_ordercart_proto_rawDescGZIP(), []int{2}
}

func (x *OrderCostResponse) GetCost() string {
	if x != nil {
		return x.Cost
	}
	return ""
}

var File_ordercart_ordercart_proto protoreflect.FileDescriptor

var file_ordercart_ordercart_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x63, 0x61, 0x72, 0x74, 0x2f, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x63, 0x61, 0x72, 0x74, 0x22, 0x37, 0x0a, 0x10, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x04, 0x63, 0x61,
	0x72, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x63, 0x61, 0x72, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x63, 0x61, 0x72, 0x74, 0x22,
	0x1a, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x11, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x6f, 0x73, 0x74, 0x32, 0x58, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x61, 0x72,
	0x74, 0x12, 0x4b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x73,
	0x74, 0x12, 0x1b, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x43, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x15,
	0x5a, 0x13, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x63, 0x61, 0x72, 0x74, 0x2f, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x63, 0x61, 0x72, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ordercart_ordercart_proto_rawDescOnce sync.Once
	file_ordercart_ordercart_proto_rawDescData = file_ordercart_ordercart_proto_rawDesc
)

func file_ordercart_ordercart_proto_rawDescGZIP() []byte {
	file_ordercart_ordercart_proto_rawDescOnce.Do(func() {
		file_ordercart_ordercart_proto_rawDescData = protoimpl.X.CompressGZIP(file_ordercart_ordercart_proto_rawDescData)
	})
	return file_ordercart_ordercart_proto_rawDescData
}

var file_ordercart_ordercart_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ordercart_ordercart_proto_goTypes = []interface{}{
	(*OrderCostRequest)(nil),  // 0: ordercart.OrderCostRequest
	(*Item)(nil),              // 1: ordercart.Item
	(*OrderCostResponse)(nil), // 2: ordercart.OrderCostResponse
}
var file_ordercart_ordercart_proto_depIdxs = []int32{
	1, // 0: ordercart.OrderCostRequest.cart:type_name -> ordercart.Item
	0, // 1: ordercart.OrderCart.GetOrderCost:input_type -> ordercart.OrderCostRequest
	2, // 2: ordercart.OrderCart.GetOrderCost:output_type -> ordercart.OrderCostResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ordercart_ordercart_proto_init() }
func file_ordercart_ordercart_proto_init() {
	if File_ordercart_ordercart_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ordercart_ordercart_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ordercart_ordercart_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ordercart_ordercart_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ordercart_ordercart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ordercart_ordercart_proto_goTypes,
		DependencyIndexes: file_ordercart_ordercart_proto_depIdxs,
		MessageInfos:      file_ordercart_ordercart_proto_msgTypes,
	}.Build()
	File_ordercart_ordercart_proto = out.File
	file_ordercart_ordercart_proto_rawDesc = nil
	file_ordercart_ordercart_proto_goTypes = nil
	file_ordercart_ordercart_proto_depIdxs = nil
}
